services:
  - type: web
    name: your-bot-name
    runtime: python
    pythonVersion: 3.12  # ← ВАЖНО!
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromEnv: TELEGRAM_BOT_TOKEN
      - key: RENDER_SERVICE_URL
        fromEnv: RENDER_SERVICE_URL

